go:
    version: 1.12.0
    cgo: false
repository:
    path: github.com/mitchellrj/hue_exporter
build:
    flags: -a -tags 'netgo static_build'
    ldflags: |
        -s
        -w
        -extldflags "-static"
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Version={{.Version}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Revision={{.Revision}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.Branch={{.Branch}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildUser={{user}}
        -X {{repoPath}}/vendor/github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
crossbuild:
  platforms:
    - darwin/amd64
    - linux/amd64
    - linux/armv6
    - linux/armv7
    - linux/arm64
